USE daelim;

CREATE TABLE IF NOT EXISTS MEMBER (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    EMAIL VARCHAR(255) NOT NULL,
    PASSWORD VARCHAR(100) NOT NULL,
    NAME VARCHAR(100) NOT NULL,
    REGDATE DATETIME NOT NULL,
    UNIQUE KEY UK_MEMBER_EMAIL (EMAIL)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

INSERT INTO MEMBER (EMAIL, PASSWORD, NAME, REGDATE)
SELECT 'a@a.com', '1234', 'AAA', NOW()
WHERE NOT EXISTS (
    SELECT 1 FROM MEMBER WHERE EMAIL = 'a@a.com'
);
